POST http://localhost:3003/api/users HTTP/1.1
Content-Type: application/json

{
  "username": "ep@ep.org",
  "name": "Emma Phillips",
  "password": "someotherpassword"
}

###

POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "ep@ep.org",
  "password": "someotherpassword"
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVwQGVwLm9yZyIsImlkIjoiNjI4NGI4NTZmMDYwZDA0NzA0M2Y5MDYyIiwiaWF0IjoxNjUyODY1MTEzfQ._NfCH268PZSt_RCzmZZslUMUq0g5Ee6z2rjg6yyRTeo

{
  "title": "Amber's a liar",
  "author": "Emma",
  "url": "xxx",
  "userId": "6284b856f060d047043f9062"
}

###

DELETE http://localhost:3003/api/blogs/6284b881f060d047043f9067
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVwQGVwLm9yZyIsImlkIjoiNjI4NGI4NTZmMDYwZDA0NzA0M2Y5MDYyIiwiaWF0IjoxNjUyODY1MTEzfQ._NfCH268PZSt_RCzmZZslUMUq0g5Ee6z2rjg6yyRTeo